# Generated by Django 4.2.1 on 2023-05-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("coach", "Coach"),
                    ("gk", "Goalkeeper"),
                    ("def", "Defender"),
                    ("mid", "Midfielder"),
                    ("st", "Striker"),
                ]
            ),
        ),
    ]
