# Generated by Django 4.2.1 on 2023-05-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0003_alter_player_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
