# Generated by Django 4.2.1 on 2023-05-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0004_team_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("0", "Coach"),
                    ("1", "Goalkeeper"),
                    ("2", "Defender"),
                    ("3", "Midfielder"),
                    ("4", "Striker"),
                ]
            ),
        ),
    ]
