# Generated by Django 4.2.1 on 2023-05-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0007_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerGoals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goals", models.SmallIntegerField(max_length=2)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="football.match"
                    ),
                ),
                (
                    "scorer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="football.player",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="goal_scorers",
            field=models.ManyToManyField(
                through="football.PlayerGoals", to="football.player"
            ),
        ),
    ]
