# Generated by Django 4.2.1 on 2023-05-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0009_alter_playergoals_goals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="points",
        ),
        migrations.CreateModel(
            name="LeagueTeamPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="football.league",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="football.team"
                    ),
                ),
            ],
        ),
    ]
