# Generated by Django 4.2.1 on 2023-05-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0010_remove_team_points_leagueteampoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamleague",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="LeagueTeamPoints",
        ),
    ]
