# Generated by Django 4.2.1 on 2023-05-24 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0011_teamleague_points_delete_leagueteampoints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="team_away_goals",
            field=models.SmallIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team_home_goals",
            field=models.SmallIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="playergoals",
            name="goals",
            field=models.SmallIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
