# Generated by Django 4.2.1 on 2023-05-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0012_alter_match_team_away_goals_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="team_away_goals",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="match",
            name="team_home_goals",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="playergoals",
            name="goals",
            field=models.SmallIntegerField(),
        ),
    ]
