# Generated by Django 4.2.1 on 2023-05-24 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0013_alter_match_team_away_goals_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playergoals",
            name="goals",
        ),
        migrations.AddField(
            model_name="playergoals",
            name="goal",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="playergoals",
            name="minute",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
            preserve_default=False,
        ),
    ]
