# Generated by Django 4.2.1 on 2023-05-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0014_remove_playergoals_goals_playergoals_goal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playergoals",
            name="minute",
            field=models.SmallIntegerField(),
        ),
    ]
